name: deploy-develop

on:
  push:
    branches:
      - develop
  workflow_dispatch:  # 수동 실행 가능

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      EC2_USER: ubuntu
      EC2_HOST: ${{ secrets.EC2_HOST }}
      EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          echo "$EC2_SSH_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

          cat >>~/.ssh/config <<END
          Host umc_home_master
            HostName $EC2_HOST
            User $EC2_USER
            IdentityFile ~/.ssh/id_rsa
            StrictHostKeyChecking no
          END

      - name: Copy Workspace
        run: |
          ssh umc_home_master 'sudo mkdir -p /opt/app'
          ssh umc_home_master 'sudo chown ubuntu:ubuntu /opt/app'
          scp -r ./[!.]* umc_home_master:/opt/app

      - name: Install dependencies
        run: |
          ssh umc_home_master 'cd /opt/app && npm install'

      - name: Copy systemd service file
        run: |
          ssh umc_home_master '
            echo "[Unit]
            Description=umc_home_master
            After=network.target

            [Service]
            User=ubuntu
            WorkingDirectory=/opt/app
            ExecStart=/usr/bin/npm run start
            Restart=always
            Environment=NODE_ENV=production

            [Install]
            WantedBy=multi-user.target" | sudo tee /etc/systemd/system/app.service
          '

      - name: Enable systemd service
        run: |
          ssh umc_home_master 'sudo systemctl daemon-reload'
          ssh umc_home_master 'sudo systemctl enable app'

      - name: Run Prisma Migrations
        run: |
          ssh umc_home_master 'cd /opt/app && npx prisma generate'
          ssh umc_home_master 'cd /opt/app && npx prisma migrate deploy'

      - name: Restart systemd service
        run: |
          ssh umc_home_master 'sudo systemctl restart app'
